services:
  catalog.api:
    container_name: catalogapi
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP=8080
      - ASPNETCORE_HTTPS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    ports:
      - '6000:8080'
      - '6060:8081'
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
    depends_on:
      - catalogdb

  basket.api:
    container_name: basketapi
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP=8080
      - ASPNETCORE_HTTPS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=http://discountgrpc:8080
    ports:
      - '6001:8080'
      - '6061:8081'
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
    depends_on:
      - basketdb
      - distributedcache
      - discountgrpc

  discountgrpc:
    container_name: discountgrpc
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP=8080
      - ASPNETCORE_HTTPS=8081
      - ConnectionStrings__Database=Data Source=discountdb
    ports:
      - '6002:8080'
      - '6062:8081'
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro

  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - '5432:5432'
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    ports:
      - '5433:5432'
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    ports:
      - '1432:1433'

  distributedcache:
    image: redis
    container_name: distributedcache
    ports:
      - '6379:6379'

volumes:
  postgres_catalog:
  postgres_basket:
